name: dao

plugins:
  - name: alchemy
    version: 0.6.2
  - name: etherscan
    version: 0.6.11
  - name: solidity
    version: 0.6.9
  - name: foundry
    version: 0.6.12

default_ecosystem: ethereum

ethereum:
  default_network: local
  local:
    default_provider: foundry

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.3
  - name: openzeppelin-2.3.0
    github: OpenZeppelin/openzeppelin-contracts
    version: 2.3.0

solidity:
  via_ir: true
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.3"
    - "@openzeppelin-solidity-2.3.0/contracts=openzeppelin-2.3.0/v2.3.0"
